#+TITLE: The Elephant in the Room
#+DATE: 2019-02-22
#+AUTHOR: W Max Zimmerman
#+EMAIL: william.m.zimmerman+pres@gmail.com
#+LANG: en
#+EXCLUDE_TAGS: noexport

* Intro
** Story
- My wife and I recently had our first child, Korra
- She is rather good most of the time, but sometimes during the night she wakes up and starts crying
- When she starts crying, we both wake up and start trying to think of solutions
  - Disclaimer: More experienced parents may have handled this differently, but as I mentioned this is our first child
** Solutions
- Does she need gas medicine?
- Is she hungry?
- Did she get hurt?
** Outcome 
We would think of all the possible solution, but they were almost always wrong
** Real Solution
In the end she typically just want to hold her stuffed elephant
* Conclusion
** Problem
- Too often people get caught up in trying to 'Save the World' when all that is need is taking out the trash
- Lets stop focusing all of the things that we 'could' do and instead focus on the problems we are trying to solve
** Questions?
