name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Dotnet 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Use Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Set Run Permissions for Scripts
      run: sudo chmod +x ./infra/scripts/*

    - name: Run a one-line script
      run: ./infra/scripts/publish-target.sh ./public
      

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run a multi-line script
      run: ./infra/scripts/cdk-deploy.sh
